fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: 'noreply@example.com'
        sender_name: 'Admin System'
    service:
        mailer: fos_user.mailer.noop
    registration:
        confirmation:
            enabled: false
    resetting:
        email:
            from_email:
                address: 'noreply@example.com'
                sender_name: 'Admin System'
            template: '@FOSUser/Resetting/email.txt.twig' 