fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    service:
        mailer: fos_user.mailer.noop
    from_email:
        address: "noreply@example.com"
        sender_name: "Admin"
    registration:
        confirmation:
            enabled: false  # Disable email confirmation
    resetting:
        email:
            from_email:
                address: "noreply@example.com"
                sender_name: "Admin"
            # enabled: false  # Disable password resetting 