<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250428183241 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE returns (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tax_id VARCHAR(15) NOT NULL, brand VARCHAR(100) DEFAULT 'Miles' NOT NULL, sku VARCHAR(100) NOT NULL, sales_date DATE NOT NULL, return_date DATE NOT NULL, quantity INT DEFAULT 1 NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_8B164CA5B2A824D8 ON returns (tax_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_8B164CA51C52F958 ON returns (brand)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_8B164CA5F9038C4 ON returns (sku)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_8B164CA55709DAAF ON returns (sales_date)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_8B164CA5CB688793 ON returns (return_date)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE sales (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tax_id VARCHAR(15) DEFAULT NULL, sales_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, brand VARCHAR(100) DEFAULT 'Miles', sku VARCHAR(100) NOT NULL, quantity INT DEFAULT 1 NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_6B817044B2A824D8 ON sales (tax_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_6B8170441C52F958 ON sales (brand)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_6B817044F9038C4 ON sales (sku)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_6B8170445709DAAF ON sales (sales_date)
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE sale
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE return_data
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stock ADD brand VARCHAR(100) DEFAULT 'Miles' NOT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stock ADD sku VARCHAR(100) NOT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stock ADD stock_date DATE NOT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stock DROP product
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stock ALTER quantity SET DEFAULT 1
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_4B3656601C52F958 ON stock (brand)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_4B365660F9038C4 ON stock (sku)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_4B365660B3846FBE ON stock (stock_date)
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE sale (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, product VARCHAR(255) NOT NULL, quantity INT NOT NULL, amount DOUBLE PRECISION NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE return_data (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, product VARCHAR(255) NOT NULL, quantity INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE returns
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE sales
        SQL);
        $this->addSql(<<<'SQL'
            DROP INDEX IDX_4B3656601C52F958
        SQL);
        $this->addSql(<<<'SQL'
            DROP INDEX IDX_4B365660F9038C4
        SQL);
        $this->addSql(<<<'SQL'
            DROP INDEX IDX_4B365660B3846FBE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stock ADD product VARCHAR(255) NOT NULL
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stock DROP brand
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stock DROP sku
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stock DROP stock_date
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE stock ALTER quantity DROP DEFAULT
        SQL);
    }
}
