<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250507144840 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE fos_user (username VARCHAR(180) NOT NULL, username_canonical VARCHAR(180) NOT NULL, email VARCHAR(180) NOT NULL, email_canonical VARCHAR(180) NOT NULL, enabled BOOLEAN NOT NULL, salt VARCHAR(255) DEFAULT NULL, password VARCHAR(255) NOT NULL, last_login TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, confirmation_token VARCHAR(180) DEFAULT NULL, password_requested_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, roles JSON NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_957A647992FC23A8 ON fos_user (username_canonical)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_957A6479A0D96FBF ON fos_user (email_canonical)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_957A6479C05FB297 ON fos_user (confirmation_token)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE returns (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tax_id VARCHAR(15) NOT NULL, brand VARCHAR(100) DEFAULT 'Miles' NOT NULL, sku VARCHAR(100) NOT NULL, sales_date DATE NOT NULL, return_date DATE NOT NULL, quantity INT DEFAULT 1 NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_8B164CA5B2A824D8 ON returns (tax_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_8B164CA51C52F958 ON returns (brand)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_8B164CA5F9038C4 ON returns (sku)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_8B164CA55709DAAF ON returns (sales_date)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_8B164CA5CB688793 ON returns (return_date)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE sales (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tax_id VARCHAR(15) DEFAULT NULL, sales_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, brand VARCHAR(100) DEFAULT 'Miles', sku VARCHAR(100) NOT NULL, quantity INT DEFAULT 1 NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_6B817044B2A824D8 ON sales (tax_id)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_6B8170441C52F958 ON sales (brand)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_6B817044F9038C4 ON sales (sku)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_6B8170445709DAAF ON sales (sales_date)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE settings (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(255) NOT NULL, value TEXT DEFAULT NULL, comment TEXT DEFAULT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX UNIQ_E545A0C577153098 ON settings (code)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_E545A0C577153098 ON settings (code)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE stocks (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, brand VARCHAR(100) DEFAULT 'Miles' NOT NULL, sku VARCHAR(100) NOT NULL, stock_date DATE NOT NULL, quantity INT DEFAULT 1 NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_56F798051C52F958 ON stocks (brand)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_56F79805F9038C4 ON stocks (sku)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE INDEX IDX_56F79805B3846FBE ON stocks (stock_date)
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            DROP TABLE fos_user
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE returns
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE sales
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE settings
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE stocks
        SQL);
    }
}
