<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250427174517 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE return_data (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, product VARCHAR(255) NOT NULL, quantity INT NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE sale (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, product VARCHAR(255) NOT NULL, quantity INT NOT NULL, amount DOUBLE PRECISION NOT NULL, PRIMARY KEY(id))
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE stock (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, product VARCHAR(255) NOT NULL, quantity INT NOT NULL, PRIMARY KEY(id))
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            DROP TABLE return_data
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE sale
        SQL);
        $this->addSql(<<<'SQL'
            DROP TABLE stock
        SQL);
    }
}
