controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

admin_dashboard:
    resource: App\Controller\Admin\DashboardController
    type: attribute
    prefix: /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

api_platform:
    resource: .
    type: api_platform
    prefix: /api
