# Homepage route must be first
homepage:
    path: /
    controller: App\Controller\HomepageController::index
    methods: [GET]

# Admin routes
admin:
    resource: ../src/Controller/Admin/
    type: attribute
    prefix: /admin

# Main controllers
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# API Platform routes
api_platform:
    resource: .
    type: api_platform
    prefix: /api

# FOSUser routes
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# API Sales Data routes
api_salesdata:
    resource: '../src/Controller/Api/'
    type: attribute
    prefix: /api/salesdata