services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    App\Tests\DataFixtures\:
        resource: '../tests/DataFixtures/'
        tags: ['doctrine.fixture.orm'] 