<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUNl1b5V\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUNl1b5V/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUNl1b5V.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUNl1b5V\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUNl1b5V\App_KernelDevDebugContainer([
    'container.build_hash' => 'UNl1b5V',
    'container.build_id' => '390d59e1',
    'container.build_time' => 1745483975,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUNl1b5V');
